# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blood_type.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x62lood_type.proto\x12\nhelloworld*(\n\tBloodType\x12\x05\n\x01\x41\x10\x00\x12\x05\n\x01\x42\x10\x01\x12\x05\n\x01O\x10\x02\x12\x06\n\x02\x41\x42\x10\x03\x62\x06proto3')

_BLOODTYPE = DESCRIPTOR.enum_types_by_name['BloodType']
BloodType = enum_type_wrapper.EnumTypeWrapper(_BLOODTYPE)
A = 0
B = 1
O = 2
AB = 3


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BLOODTYPE._serialized_start=32
  _BLOODTYPE._serialized_end=72
# @@protoc_insertion_point(module_scope)
