[package]
name = "hello-grpc-tonic"
version = "0.1.0"
authors = ["Ken Sato <ksato9700@gmail.com>"]
edition = "2018"
build = "build.rs"

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/client.rs"

[dependencies]
tonic = "0.7.2"
prost = "0.10.4"
tokio = { version = "1.20.1", features = ["full"] }
futures = { version = "0.3.21", default-features = false, features = ["alloc"] }

[build-dependencies]
tonic-build = { version="0.7.2", features = ["prost"] }
