steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - "--tag=asia-northeast1-docker.pkg.dev/$PROJECT_ID/sandbox/greeter-server-rust"
      - .

timeout: 12000s
images:
  - "asia-northeast1-docker.pkg.dev/$PROJECT_ID/sandbox/greeter-server-rust"
options:
  machineType: "N1_HIGHCPU_8"
