/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package helloworld;

import org.junit.Test;
import static org.junit.Assert.*;

public class HelloWorldClientTest {
    @Test
    public void testHelloWorldClientHasAGreeting() {
        // HelloWorldClient classUnderTest = new HelloWorldClient();
        // assertNotNull("HelloWorldClient should have a greeting",
        // classUnderTest.getGreeting());
    }
}
